services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user-service
    container_name: medicare-user-service
    ports:
      - "8082:8082"
    networks:
      - medicare-network
    restart: unless-stopped
    environment:
      DATABASE_ENDPOINT: "jdbc:postgresql://user-postgres:5432/user_service_db"
      USER_SERVICE_URL: "http://localhost:8082"

  user-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: user_service_pass
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - medicare-network
    restart: unless-stopped

volumes:
  user_postgres_data:
