spring.application.name=ClassInsight

# Configuração do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:classinsightdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Servidor
server.port=8080
server.servlet.context-path=/classinsight

# Logging
logging.level.root=INFO
logging.level.br.com.grupo.ClassInsight=DEBUG
