server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://user-postgres:5432/user_service_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}