server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://scheduler-postgres:5432/scheduling-service
    driver-class-name: org.postgresql.Driver
    username: scheduler_user
    password: scheduler_pass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      client-id: scheduling-service
    consumer:
      group-id: scheduling-service

user-service:
  url: http://user-service:8082

jwt:
  secret: prod-local-key-2024-fiap-tech-challenge

kafka:
  topics:
    notification: cliente-agendamento-notificar
